''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
'@desc     Proposed additional tests for Excel-VBA-Dicts
'           Each Sub corresponds to one coverage gap identified in the
'           test-coverage analysis.  Run them from the VBA IDE with
'           F5 (or call them from a master runner Sub).
'
'           Requires: Dicts, Lists, HashSets, TreeSets, Nodes modules
'@author   Generated by coverage analysis – 2026-03-23
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

Option Explicit

' =====================================================================
' MASTER RUNNER
' Call this Sub to execute every proposed test suite in sequence.
' =====================================================================
Public Sub RunAllProposedTests()
    TestLists_StatisticalOps
    TestLists_SliceTakeDrop
    TestLists_IndexOf
    TestLists_SomeEvery
    TestLists_ZipAndFlatten
    TestLists_StringOps
    TestLists_Mutation
    TestLists_ReduceRight
    TestLists_Product
    TestLists_EdgeCases
    TestDicts_Intersect
    TestDicts_Update
    TestDicts_LeftJoin
    TestJSON_FromJSON_Primitives
    TestJSON_FromJSON_Object
    TestJSON_FromJSON_Array
    TestJSON_FromJSON_Nested
    TestJSON_FromJSON_Strings
    TestJSON_RoundTrip
    TestDicts_FrequencyCount
    TestDicts_Nulls
    TestDicts_Remove
    TestDicts_UnionKeepOriginalFalse
    TestDicts_RecursiveCount
    TestDicts_LabelOps
    TestDicts_IsNothing
    TestHashSets_BasicOps
    TestHashSets_DuplicateRejection
    TestTreeSets_PollFirstLast
    TestTreeSets_SubSet
    TestTreeSets_SizeIsEmptyFirstLast
    TestTreeSets_Remove
    TestTreeSets_CeilingBoundary
    Debug.Print "=== All proposed tests passed! ==="
End Sub


' =====================================================================
' SECTION 1 – Lists: Statistical operations
' Currently untested: min_(), max_(), avg()
' =====================================================================
Public Sub TestLists_StatisticalOps()
    Dim l As New Lists

    ' min_
    Debug.Assert l.fromSerial(3, 7).min_ = 3
    Debug.Assert l.fromArray(Array(10, 2, 7, 1, 5)).min_ = 1

    ' max_
    Debug.Assert l.fromSerial(3, 7).max_ = 7
    Debug.Assert l.fromArray(Array(10, 2, 7, 1, 5)).max_ = 10

    ' avg
    Debug.Assert l.fromArray(Array(1, 2, 3, 4, 5)).avg = 3

    ' single-element edge cases
    Debug.Assert l.fromArray(Array(42)).min_ = 42
    Debug.Assert l.fromArray(Array(42)).max_ = 42
    Debug.Assert l.fromArray(Array(42)).avg = 42

    Debug.Print "TestLists_StatisticalOps passed"
End Sub


' =====================================================================
' SECTION 2 – Lists: slice / take / drop / dropLast
' These are used internally (e.g. inside removeAt) but never directly
' asserted in the existing test suite.
' =====================================================================
Public Sub TestLists_SliceTakeDrop()
    Dim l As New Lists

    ' slice with explicit indices
    Debug.Assert l.fromSerial(1, 5).slice(1, 3).length = 2          ' [2, 3]
    Debug.Assert l.fromSerial(1, 5).slice(1, 3).getVal(0) = 2

    ' negative index: slice from the end
    Debug.Assert l.fromSerial(1, 5).slice(-2).length = 2            ' [4, 5]
    Debug.Assert l.fromSerial(1, 5).slice(-2).getVal(0) = 4

    ' take
    Debug.Assert l.fromSerial(1, 10).take(3).length = 3
    Debug.Assert l.fromSerial(1, 10).take(3).getVal(2) = 3

    ' drop
    Debug.Assert l.fromSerial(1, 5).drop(2).length = 3
    Debug.Assert l.fromSerial(1, 5).drop(2).getVal(0) = 3

    ' dropLast
    Debug.Assert l.fromSerial(1, 5).dropLast(2).length = 3
    Debug.Assert l.fromSerial(1, 5).dropLast(2).getVal(2) = 3

    ' take(0) -> empty list
    Debug.Assert l.fromSerial(1, 5).take(0).length = 0

    Debug.Print "TestLists_SliceTakeDrop passed"
End Sub


' =====================================================================
' SECTION 3 – Lists: indexOf
' True and false (not-found) cases are both unverified.
' =====================================================================
Public Sub TestLists_IndexOf()
    Dim l As New Lists
    Set l = l.fromSerial(10, 15)

    ' present element returns correct 0-based index
    Debug.Assert l.indexOf(10) = 0
    Debug.Assert l.indexOf(12) = 2
    Debug.Assert l.indexOf(15) = 5

    ' absent element returns -1
    Debug.Assert l.indexOf(99) = -1
    Debug.Assert l.indexOf(9) = -1

    ' contains false case (not verified in existing tests)
    Debug.Assert Not l.contains(99)

    Debug.Print "TestLists_IndexOf passed"
End Sub


' =====================================================================
' SECTION 4 – Lists: some() / every()
' =====================================================================
Public Sub TestLists_SomeEvery()
    Dim l As New Lists

    ' some – at least one element matches
    Debug.Assert l.fromSerial(1, 5).some("_>4")     ' 5 > 4
    Debug.Assert Not l.fromSerial(1, 5).some("_>10")

    ' every – all elements match
    Debug.Assert l.fromSerial(1, 5).every("_>0")
    Debug.Assert Not l.fromSerial(1, 5).every("_>2")

    ' edge: single element
    Debug.Assert l.of(7).some("_=7")
    Debug.Assert l.of(7).every("_>0")

    Debug.Print "TestLists_SomeEvery passed"
End Sub


' =====================================================================
' SECTION 5 – Lists: zip() / zipMe() / flatten()
' zip() is used to build test data for fromMatrix but is never directly
' asserted.  flatten() and zipMe() are completely untested.
' =====================================================================
Public Sub TestLists_ZipAndFlatten()
    Dim l As New Lists
    Dim a As New Lists
    Dim b As New Lists

    ' zip two lists into list-of-pairs
    Set a = l.fromSerial(1, 3)
    Set b = l.fromSerial(4, 6)
    With a.zip(b)
        Debug.Assert .length = 3
        Debug.Assert .getVal(0, 0) = 1
        Debug.Assert .getVal(0, 1) = 4
        Debug.Assert .getVal(2, 0) = 3
        Debug.Assert .getVal(2, 1) = 6
    End With

    ' flatten: [[1,2],[3,4]] -> [1,2,3,4]
    Dim nested As New Lists
    nested.add l.of(1, 2)
    nested.add l.of(3, 4)
    With nested.flatten
        Debug.Assert .length = 4
        Debug.Assert .getVal(0) = 1
        Debug.Assert .getVal(3) = 4
    End With

    ' zipMe (transpose a list-of-lists)
    Dim matrix As New Lists
    matrix.add l.of(1, 2, 3)
    matrix.add l.of(4, 5, 6)
    With matrix.zipMe
        Debug.Assert .length = 3               ' 3 columns -> 3 rows after transpose
        Debug.Assert .getVal(0, 0) = 1
        Debug.Assert .getVal(0, 1) = 4
    End With

    Debug.Print "TestLists_ZipAndFlatten passed"
End Sub


' =====================================================================
' SECTION 6 – Lists: string utilities (fromString / join)
' =====================================================================
Public Sub TestLists_StringOps()
    Dim l As New Lists

    ' fromString: every character becomes an element
    With l.fromString("hello")
        Debug.Assert .length = 5
        Debug.Assert .getVal(0) = "h"
        Debug.Assert .getVal(4) = "o"
    End With

    ' join: concatenate with delimiter
    Debug.Assert l.fromSerial(1, 3).join(",") = "1,2,3"
    Debug.Assert l.fromArray(Array("a", "b", "c")).join("-") = "a-b-c"

    ' join with empty delimiter
    Debug.Assert l.fromString("abc").join("") = "abc"

    Debug.Print "TestLists_StringOps passed"
End Sub


' =====================================================================
' SECTION 7 – Lists: in-place mutation (addAt, removeAt, repeat)
' =====================================================================
Public Sub TestLists_Mutation()
    Dim l As New Lists

    ' addAt – insert at position
    l.fromSerial(1, 3).addAt 99, 1
    ' [1, 99, 2, 3]  length = 4
    Debug.Assert l.length = 4
    Debug.Assert l.getVal(1) = 99
    Debug.Assert l.getVal(2) = 2

    ' removeAt – remove by position
    l.fromSerial(1, 5).removeAt 2
    ' [1, 2, 4, 5]
    Debug.Assert l.length = 4
    Debug.Assert l.getVal(2) = 4

    ' repeat – create list with repeated value
    With l.repeat(7, 4)
        Debug.Assert .length = 4
        Debug.Assert .getVal(0) = 7
        Debug.Assert .getVal(3) = 7
    End With

    Debug.Print "TestLists_Mutation passed"
End Sub


' =====================================================================
' SECTION 8 – Lists: reduceRight()
' Reduces from the right; order matters for non-commutative operations.
' =====================================================================
Public Sub TestLists_ReduceRight()
    Dim l As New Lists

    ' For subtraction: right-fold [1,2,3] with (acc - cur) from the right
    ' reduceRight("?-_", 0): 0 - 3 = -3; -3 - 2 = -5; -5 - 1 = -6
    Debug.Assert l.fromArray(Array(1, 2, 3)).reduceRight("?-_", 0) = -6

    ' Sanity: for commutative operation result should be same as reduce
    Debug.Assert l.fromArray(Array(1, 2, 3, 4)).reduceRight("?+_", 0) = _
                 l.fromArray(Array(1, 2, 3, 4)).reduce("?+_", 0)

    Debug.Print "TestLists_ReduceRight passed"
End Sub


' =====================================================================
' SECTION 9 – Lists: product()
' Element-wise operation between two lists; completely untested.
' =====================================================================
Public Sub TestLists_Product()
    Dim l As New Lists

    ' element-wise multiply
    With l.fromArray(Array(1, 2, 3)).product("_*?", l.fromArray(Array(4, 5, 6)))
        Debug.Assert .length = 3
        Debug.Assert .getVal(0) = 4
        Debug.Assert .getVal(1) = 10
        Debug.Assert .getVal(2) = 18
    End With

    ' mismatched lengths: stops at shorter list
    With l.fromSerial(1, 5).product("_+?", l.fromSerial(1, 3))
        Debug.Assert .length = 3
    End With

    Debug.Print "TestLists_Product passed"
End Sub


' =====================================================================
' SECTION 10 – Lists: empty-collection edge cases
' =====================================================================
Public Sub TestLists_EdgeCases()
    Dim l As New Lists

    ' fresh list is empty
    Debug.Assert l.length = 0
    Debug.Assert l.isEmptyList()
    Debug.Assert l.isOneDimensional()

    ' contains on empty list
    Debug.Assert Not l.contains(1)

    ' fromSerial with start = end (single element)
    Debug.Assert l.fromSerial(5, 5).length = 1
    Debug.Assert l.fromSerial(5, 5).getVal(0) = 5

    ' clear restores length
    l.fromSerial(1, 10)
    l.clear
    Debug.Assert l.length = 0

    Debug.Print "TestLists_EdgeCases passed"
End Sub


' =====================================================================
' SECTION 11 – Dicts: intersect()
' Returns only keys that exist in both dicts.
' =====================================================================
Public Sub TestDicts_Intersect()
    Dim d1 As New Dicts
    Dim d2 As New Dicts
    Dim l As New Lists

    d1.add 1, "a" : d1.add 2, "b" : d1.add 3, "c"
    d2.add 2, "x" : d2.add 3, "y" : d2.add 4, "z"

    With d1.intersect(d2)
        Debug.Assert .Count = 2
        Debug.Assert .exists(2)
        Debug.Assert .exists(3)
        Debug.Assert Not .exists(1)
        Debug.Assert Not .exists(4)
        ' by default keeps value from d1 (keepOriginalVal = True)
        Debug.Assert .Item(2) = "b"
    End With

    ' keepOriginalVal = False -> use values from d2
    With d1.intersect(d2, False)
        Debug.Assert .Item(2) = "x"
    End With

    ' empty intersection
    Dim d3 As New Dicts
    d3.add 9, "z"
    Debug.Assert d1.intersect(d3).Count = 0

    Debug.Print "TestDicts_Intersect passed"
End Sub


' =====================================================================
' SECTION 12 – Dicts: update()
' Like union but always overwrites with new values.
' =====================================================================
Public Sub TestDicts_Update()
    Dim d1 As New Dicts
    Dim d2 As New Dicts

    d1.add 1, "old1" : d1.add 2, "old2"
    d2.add 2, "new2" : d2.add 3, "new3"

    With d1.update(d2)
        Debug.Assert .Count = 3
        ' key 2 should be overwritten by d2's value
        Debug.Assert .Item(2) = "new2"
        ' key 1 stays from d1
        Debug.Assert .Item(1) = "old1"
        ' key 3 added from d2
        Debug.Assert .Item(3) = "new3"
    End With

    Debug.Print "TestDicts_Update passed"
End Sub


' =====================================================================
' SECTION 13 – Dicts: leftJoin()
' Keys from left dict; values from both, with a default for missing keys.
' =====================================================================
Public Sub TestDicts_LeftJoin()
    Dim d1 As New Dicts
    Dim d2 As New Dicts

    d1.add "A", 1 : d1.add "B", 2 : d1.add "C", 3
    d2.add "A", 10 : d2.add "C", 30

    With d1.leftJoin(d2)
        Debug.Assert .Count = 3                      ' only left-dict keys
        ' "A" exists in both -> values concatenated into a list
        Debug.Assert .Item("A").length = 2
        Debug.Assert .Item("A").getVal(0) = 1
        Debug.Assert .Item("A").getVal(1) = 10
        ' "B" missing from d2 -> padded with default (0)
        Debug.Assert .Item("B").length = 2
        Debug.Assert .Item("B").getVal(1) = 0
        ' "C" exists in both
        Debug.Assert .Item("C").getVal(1) = 30
    End With

    ' custom default for missing keys
    With d1.leftJoin(d2, defaultByNull:=-1)
        Debug.Assert .Item("B").getVal(1) = -1
    End With

    Debug.Print "TestDicts_LeftJoin passed"
End Sub


' =====================================================================
' SECTION 14 – Dicts: frequencyCount()
' Counts occurrences of each element in an array/collection.
' =====================================================================
Public Sub TestDicts_FrequencyCount()
    Dim d As New Dicts

    With d.frequencyCount(Array("a", "b", "a", "c", "a", "b"))
        Debug.Assert .Count = 3
        Debug.Assert .Item("a") = 3
        Debug.Assert .Item("b") = 2
        Debug.Assert .Item("c") = 1
    End With

    ' all unique values -> each count = 1
    With d.frequencyCount(Array(1, 2, 3, 4, 5))
        Debug.Assert .Count = 5
        Debug.Assert .Item(1) = 1
    End With

    ' single repeated value
    With d.frequencyCount(Array("x", "x", "x"))
        Debug.Assert .Count = 1
        Debug.Assert .Item("x") = 3
    End With

    Debug.Print "TestDicts_FrequencyCount passed"
End Sub


' =====================================================================
' SECTION 15 – Dicts: nulls()
' Removes empty-valued entries (or replaces them).
' =====================================================================
Public Sub TestDicts_Nulls()
    Dim d As New Dicts

    d.add 1, 10
    d.add 2, Empty     ' empty value
    d.add 3, 30
    d.add 4, Empty

    ' without argument: remove empty entries
    With d.nulls()
        Debug.Assert .Count = 2
        Debug.Assert .exists(1)
        Debug.Assert .exists(3)
        Debug.Assert Not .exists(2)
        Debug.Assert Not .exists(4)
    End With

    ' reset dict and re-add for second sub-test
    d.clear
    d.add 1, 10 : d.add 2, Empty : d.add 3, 30

    ' with toVal: replace empty entries with the specified value
    With d.nulls(toVal:=0)
        Debug.Assert .Count = 3
        Debug.Assert .Item(2) = 0
    End With

    Debug.Print "TestDicts_Nulls passed"
End Sub


' =====================================================================
' SECTION 16 – Dicts: Remove()
' Remove a key and verify it is no longer present.
' =====================================================================
Public Sub TestDicts_Remove()
    Dim d As New Dicts

    d.add 1, "a" : d.add 2, "b" : d.add 3, "c"
    d.Remove 2

    Debug.Assert d.Count = 2
    Debug.Assert Not d.exists(2)
    Debug.Assert IsNull(d.Item(2))    ' non-existent key returns Null
    Debug.Assert d.exists(1)
    Debug.Assert d.exists(3)

    ' removing a non-existent key should not raise an error
    d.Remove 99
    Debug.Assert d.Count = 2

    Debug.Print "TestDicts_Remove passed"
End Sub


' =====================================================================
' SECTION 17 – Dicts: union(keepOriginalVal:=False)
' The existing test only uses the default (keepOriginalVal = True).
' =====================================================================
Public Sub TestDicts_UnionKeepOriginalFalse()
    Dim d1 As New Dicts
    Dim d2 As New Dicts

    d1.add 1, "original" : d1.add 2, "original2"
    d2.add 2, "override" : d2.add 3, "new"

    ' keepOriginalVal = True (default): d1's value for key 2 is preserved
    Debug.Assert d1.union(d2, True).Item(2) = "original2"

    ' keepOriginalVal = False: d2's value for key 2 wins
    Debug.Assert d1.union(d2, False).Item(2) = "override"

    Debug.Print "TestDicts_UnionKeepOriginalFalse passed"
End Sub


' =====================================================================
' SECTION 18 – Dicts: Count(recursive:=True)
' Counts keys at all nesting levels.
' =====================================================================
Public Sub TestDicts_RecursiveCount()
    Dim outer As New Dicts
    Dim inner As New Dicts

    inner.add "x", 1 : inner.add "y", 2
    outer.add "A", inner
    outer.add "B", inner

    ' non-recursive: 2 top-level keys
    Debug.Assert outer.Count = 2

    ' recursive, allLevels = True: 2 parents + 2*2 children = 6
    Debug.Assert outer.Count(True, True) = 6

    ' recursive, allLevels = False: only leaf nodes = 4
    Debug.Assert outer.Count(True, False) = 4

    Debug.Print "TestDicts_RecursiveCount passed"
End Sub


' =====================================================================
' SECTION 19 – Dicts: Label operations
' hasLabel, setLabel with Array, copyLabel, label after clear
' =====================================================================
Public Sub TestDicts_LabelOps()
    Dim d As New Dicts
    Dim d2 As New Dicts

    Debug.Assert Not d.hasLabel

    d.add 1, Array(10, 20, 30)
    d.label = Array("col0", "col1", "col2")

    Debug.Assert d.hasLabel
    Debug.Assert d.getByLabel(1, "col1") = 20

    ' copyLabel
    d.copyLabel d, d2
    Debug.Assert d2.hasLabel

    ' setLabel with Nothing clears label
    d.setLabel Nothing
    Debug.Assert Not d.hasLabel

    Debug.Print "TestDicts_LabelOps passed"
End Sub


' =====================================================================
' SECTION 20 – Dicts: isNothing() – false case
' The existing test only checks isNothing("123") = False.
' =====================================================================
Public Sub TestDicts_IsNothing()
    Dim d As New Dicts

    Debug.Assert Not d.isNothing("hello")
    Debug.Assert Not d.isNothing(42)
    Debug.Assert Not d.isNothing(0)
    Debug.Assert Not d.isNothing(True)

    ' Nothing is the only truthy case
    Dim obj As Object
    Set obj = Nothing
    Debug.Assert d.isNothing(obj)

    Debug.Print "TestDicts_IsNothing passed"
End Sub


' =====================================================================
' SECTION 21 – HashSets: basic operations
' Currently zero HashSets tests exist in the test suite.
' =====================================================================
Public Sub TestHashSets_BasicOps()
    Dim h As New HashSets

    Debug.Assert h.Count = 0
    Debug.Assert h.isEmpty          ' Note: isEmpty reads pLen which must be 0

    h.add 5
    h.add 10
    h.add 3
    h.add 10                        ' duplicate – should be ignored

    Debug.Assert h.Count = 3
    Debug.Assert h.contains(5)
    Debug.Assert h.contains(10)
    Debug.Assert h.contains(3)
    Debug.Assert Not h.contains(99)

    ' first / last follow insertion order
    Debug.Assert h.first = 5
    Debug.Assert h.last = 3

    ' toArray has correct length
    Debug.Assert UBound(h.toArray) - LBound(h.toArray) + 1 = 3

    ' Remove
    h.Remove 10
    Debug.Assert h.Count = 2
    Debug.Assert Not h.contains(10)

    ' Remove non-existent element is a no-op
    h.Remove 99
    Debug.Assert h.Count = 2

    ' addAll
    h.clear
    h.addAll 1, 2, 3, 2, 1
    Debug.Assert h.Count = 3

    Debug.Print "TestHashSets_BasicOps passed"
End Sub


' =====================================================================
' SECTION 22 – HashSets: duplicate rejection
' =====================================================================
Public Sub TestHashSets_DuplicateRejection()
    Dim h As New HashSets

    Dim addResult As Boolean
    addResult = h.add(7)
    Debug.Assert addResult = True   ' first add -> True

    addResult = h.add(7)
    Debug.Assert addResult = False  ' duplicate -> False

    Debug.Assert h.Count = 1

    Debug.Print "TestHashSets_DuplicateRejection passed"
End Sub


' =====================================================================
' SECTION 23 – TreeSets: pollFirst() / pollLast()
' Remove-and-return the minimum / maximum element.
' =====================================================================
Public Sub TestTreeSets_PollFirstLast()
    Dim t As New TreeSets

    t.addAll 5, 3, 8, 1, 7

    ' pollFirst removes and returns the smallest
    Dim smallest As Variant
    smallest = t.pollFirst
    Debug.Assert smallest = 1
    Debug.Assert t.Count = 4
    Debug.Assert Not t.contains(1)

    ' pollLast removes and returns the largest
    Dim largest As Variant
    largest = t.pollLast
    Debug.Assert largest = 8
    Debug.Assert t.Count = 3
    Debug.Assert Not t.contains(8)

    Debug.Print "TestTreeSets_PollFirstLast passed"
End Sub


' =====================================================================
' SECTION 24 – TreeSets: subSet()
' Returns elements in [fromElement, toElement).
' =====================================================================
Public Sub TestTreeSets_SubSet()
    Dim t As New TreeSets

    t.addAll 1, 2, 3, 4, 5, 6, 7, 8, 9, 10

    With t.subSet(3, 7)
        Debug.Assert .Count = 4           ' 3,4,5,6  (7 is exclusive)
        Debug.Assert .contains(3)
        Debug.Assert .contains(6)
        Debug.Assert Not .contains(7)
        Debug.Assert Not .contains(2)
    End With

    Debug.Print "TestTreeSets_SubSet passed"
End Sub


' =====================================================================
' SECTION 25 – TreeSets: size / isEmpty / first / last
' =====================================================================
Public Sub TestTreeSets_SizeIsEmptyFirstLast()
    Dim t As New TreeSets

    Debug.Assert t.isEmpty
    Debug.Assert t.size = 0

    t.addAll 4, 2, 6, 1, 3, 5, 7

    Debug.Assert Not t.isEmpty
    Debug.Assert t.size = 7

    ' first and last respect sorted order
    Debug.Assert t.first = 1
    Debug.Assert t.last = 7

    Debug.Print "TestTreeSets_SizeIsEmptyFirstLast passed"
End Sub


' =====================================================================
' SECTION 26 – TreeSets: Remove()
' =====================================================================
Public Sub TestTreeSets_Remove()
    Dim t As New TreeSets

    t.addAll 10, 20, 30, 40, 50

    t.Remove 30
    Debug.Assert t.Count = 4
    Debug.Assert Not t.contains(30)

    ' Remove non-existent is a no-op
    t.Remove 99
    Debug.Assert t.Count = 4

    ' Remove first element
    t.Remove 10
    Debug.Assert t.Count = 3
    Debug.Assert Not t.contains(10)
    Debug.Assert t.first = 20

    Debug.Print "TestTreeSets_Remove passed"
End Sub


' =====================================================================
' SECTION 27 – TreeSets: ceiling() boundary cases
' The existing test only checks ceiling(14) = Null when tree max is 12.
' =====================================================================
Public Sub TestTreeSets_CeilingBoundary()
    Dim t As New TreeSets

    t.addAll 2, 4, 6, 8, 10

    ' exact match
    Debug.Assert Not IsNull(t.ceiling(4))
    Debug.Assert t.ceiling(4) >= 0        ' returns an index, not Null

    ' element above max -> Null
    Debug.Assert IsNull(t.ceiling(11))

    ' ceiling on empty set -> Null
    Dim t2 As New TreeSets
    Debug.Assert IsNull(t2.ceiling(5))

    Debug.Print "TestTreeSets_CeilingBoundary passed"
End Sub


' =====================================================================
' SECTION 28 – fromJSON: primitive values
' =====================================================================
Public Sub TestJSON_FromJSON_Primitives()
    Dim d As New Dicts

    ' null
    Debug.Assert IsNull(d.fromJSON("null"))

    ' booleans
    Debug.Assert d.fromJSON("true") = True
    Debug.Assert d.fromJSON("false") = False

    ' integers
    Debug.Assert d.fromJSON("0") = 0
    Debug.Assert d.fromJSON("42") = 42
    Debug.Assert d.fromJSON("-7") = -7

    ' float
    Debug.Assert Abs(d.fromJSON("3.14") - 3.14) < 0.0001

    ' string
    Debug.Assert d.fromJSON("""hello""") = "hello"

    Debug.Print "TestJSON_FromJSON_Primitives passed"
End Sub


' =====================================================================
' SECTION 29 – fromJSON: flat object
' =====================================================================
Public Sub TestJSON_FromJSON_Object()
    Dim d As New Dicts
    Dim json As String
    json = "{""name"":""Alice"",""age"":30,""active"":true,""score"":9.5}"

    Dim result As Dicts
    Set result = d.fromJSON(json)

    Debug.Assert result.Count = 4
    Debug.Assert result.Item("name") = "Alice"
    Debug.Assert result.Item("age") = 30
    Debug.Assert result.Item("active") = True
    Debug.Assert Abs(result.Item("score") - 9.5) < 0.0001

    ' empty object
    Dim empty As Dicts
    Set empty = d.fromJSON("{}")
    Debug.Assert empty.Count = 0

    Debug.Print "TestJSON_FromJSON_Object passed"
End Sub


' =====================================================================
' SECTION 30 – fromJSON: array
' =====================================================================
Public Sub TestJSON_FromJSON_Array()
    Dim d As New Dicts
    Dim result As Lists

    Set result = d.fromJSON("[1,2,3]")
    Debug.Assert result.length = 3
    Debug.Assert result.getVal(0) = 1
    Debug.Assert result.getVal(2) = 3

    ' mixed-type array
    Set result = d.fromJSON("[""a"",1,true,null]")
    Debug.Assert result.length = 4
    Debug.Assert result.getVal(0) = "a"
    Debug.Assert result.getVal(1) = 1
    Debug.Assert result.getVal(2) = True
    Debug.Assert IsNull(result.getVal(3))

    ' empty array
    Set result = d.fromJSON("[]")
    Debug.Assert result.length = 0

    Debug.Print "TestJSON_FromJSON_Array passed"
End Sub


' =====================================================================
' SECTION 31 – fromJSON: nested structures
' =====================================================================
Public Sub TestJSON_FromJSON_Nested()
    Dim d As New Dicts
    Dim json As String

    ' object containing array
    json = "{""items"":[10,20,30],""label"":""test""}"
    Dim res As Dicts
    Set res = d.fromJSON(json)
    Debug.Assert res.Count = 2
    Debug.Assert TypeName(res.Item("items")) = "Lists"
    Debug.Assert res.Item("items").length = 3
    Debug.Assert res.Item("items").getVal(1) = 20

    ' array of objects
    json = "[{""x"":1},{""x"":2}]"
    Dim arr As Lists
    Set arr = d.fromJSON(json)
    Debug.Assert arr.length = 2
    Debug.Assert TypeName(arr.getVal(0)) = "Dicts"
    Debug.Assert arr.getVal(0).Item("x") = 1
    Debug.Assert arr.getVal(1).Item("x") = 2

    ' two-level nested object
    json = "{""outer"":{""inner"":42}}"
    Dim nested As Dicts
    Set nested = d.fromJSON(json)
    Debug.Assert TypeName(nested.Item("outer")) = "Dicts"
    Debug.Assert nested.Item("outer").Item("inner") = 42

    Debug.Print "TestJSON_FromJSON_Nested passed"
End Sub


' =====================================================================
' SECTION 32 – fromJSON: string escape sequences
' =====================================================================
Public Sub TestJSON_FromJSON_Strings()
    Dim d As New Dicts

    ' standard escapes
    Debug.Assert d.fromJSON("""tab:\there""") = "tab:" & Chr(9) & "here"
    Debug.Assert d.fromJSON("""line\nbreak""") = "line" & Chr(10) & "break"
    Debug.Assert d.fromJSON("""quote:\""""") = "quote:"""

    ' \uXXXX Unicode escape (U+0041 = "A")
    Debug.Assert d.fromJSON("""\u0041""") = "A"

    ' whitespace around value is ignored
    Debug.Assert d.fromJSON("  ""hello""  ") = "hello"

    Debug.Print "TestJSON_FromJSON_Strings passed"
End Sub


' =====================================================================
' SECTION 33 – fromJSON / toJSON round-trip
' Serialise a Dicts with toJSON then parse back with fromJSON and
' verify the values are preserved.
' =====================================================================
Public Sub TestJSON_RoundTrip()
    Dim d As New Dicts
    Dim l As New Lists

    d.add "name", "Bob"
    d.add "score", 7.5
    d.add "active", False
    d.add "tags", l.of("vba", "excel")

    ' serialise
    Dim json As String
    json = d.toJSON

    ' parse back
    Dim d2 As Dicts
    Set d2 = d.fromJSON(json)

    Debug.Assert d2.Count = 4
    Debug.Assert d2.Item("name") = "Bob"
    Debug.Assert Abs(d2.Item("score") - 7.5) < 0.0001
    Debug.Assert d2.Item("active") = False
    Debug.Assert TypeName(d2.Item("tags")) = "Lists"
    Debug.Assert d2.Item("tags").length = 2
    Debug.Assert d2.Item("tags").getVal(0) = "vba"

    Debug.Print "TestJSON_RoundTrip passed"
End Sub
